//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicket
    {
        public int ticketid { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Prority { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ResolveDate { get; set; }
        public Nullable<bool> ResolveStatus { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
